### ISSUE TITLE
errors in zim url in json

### ISSUE THREAD

**Issue by tim-moody** [kiwix/kiwix-android-custom#10]
some have a generic name, like "zim_url": "https://download.kiwix.org/zim/wikipedia_fr_medicine.zim", and others have a specific version, 

like "zim_url": "http://download.kiwix.org/zim/wikipedia/wikipedia_en_medicine_nodet_2017-08.zim",

and at least one (ar) is the wiki, not the med wiki

"zim_url": "https://download.kiwix.org/zim/wikipedia_ar_all.zim",

**Comment by kelson42** [comment]
@tim-moody which json?

**Comment by tim-moody** [comment]
which form of the zim_url is correct, with or without the date version string?

**Comment by kelson42** [comment]
@tim-moody Both are OK. One is a redirect (permalink) to an other (width date).
