### ISSUE TITLE
Configure and release first DWDS custom app

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-android-custom#107]
First `info.js` should be:
```
{
  "app_name": "Digitales Wörterbuch der deutschen Sprache",
  "zim_url": "https://{{DWDS_HTTP_BASIC_ACCESS_AUTHENTICATION}}@www.dwds.de/kiwix/f/dwds_de_dictionary_nopic_2023-09-12.zim",
  "enforced_lang": "de"
}
```

The directory should be called `dwds`

This ticket is blocked by kiwix/kiwix-android#3499

**Comment by kelson42** [comment]
Please check first that the ZIM file can play with the current Kiwix-Android `main` branch. If not please published based on `develop`.

**Comment by MohitMaliFtechiz** [comment]
>Please check first that the ZIM file can play with the current Kiwix-Android main branch. If not please published based on develop.

@kelson42 I have tested it with the `main` branch but it is unable to load `HomePage` with the `main` branch, also I have tested it with the `develop` branch, and with the `develop` branch the zim file working fine.

@gouri-panda please upload `dwds` app with develop branch.

**Comment by gouri-panda** [comment]
@MohitMaliFtechiz Sorry I forgot that. Will do that.

**Comment by kelson42** [comment]
Can we finally have a PR for thid ticket? not only for #106
