### ISSUE TITLE
Provide solution to upload first dummy app

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-android-custom#109]
Playstore wants us to upload the first time manually the app.

The CD should be able to provide this APK to download (or is that something else which has to be built?) to download so the team can easily proceed without having to compile it manually.

Actually it can be a dummy APK as well, as long it has the necessary properties for the Playstore.

To trigger that build a specific attribute `new: true` has to be put in the `info.json`.

The APK should be made available via https://docs.github.com/en/actions/using-workflows/storing-workflow-data-as-artifacts

README should be updated

**Comment by gouri-panda** [comment]
Not relevant any more. Since we're focusing on the bundle now.

**Comment by kelson42** [comment]
This is still relevant, this is why we have an open PR... or can we upload the bundle straight? Even the first time?

**Comment by gouri-panda** [comment]
@kelson42 for manually we can't do that for the first time apk or bundle by the ci. We discussed that before. The first time the bot doesn't know the right package in the playstore because it hasn't been created yet.

**Comment by kelson42** [comment]
@gouri-panda OK, please keep tickets open as long as PR not merged
