### ISSUE TITLE
DWDS custom app does not always find the ZIM on my phone

### ISSUE THREAD

**Issue by benoit74** [kiwix/kiwix-android-custom#111]
On my phone, DWDS custom app fails to find the ZIM.

Here is what I've done:

- Before installation, there is nothing in storage at /Android/data/org.kiwix.kiwixcustomdwds

- Install the app from Play Store internal testing : https://play.google.com/apps/internaltest/4701495824507027112

![image](https://github.com/kiwix/kiwix-android-custom/assets/7102089/94d34ce1-ef56-4711-bf2f-05887909cf11)

- After installation, we have the following data in storage:

  - /Android/data/org.kiwix.kiwixcustomdwds/files/
    - Kiwix/
      - dwds_de_dictionnary_nopic_2023-09-12.zim (0 byte)

This file appeared **during the installation phase** of the Play Store, I did not started the application yet.

- Start the application, it fails

![Screenshot_20231020-083755](https://github.com/kiwix/kiwix-android-custom/assets/7102089/5793f025-d92d-437d-b298-88b1650e8740)

Logs:
[logs1697783883095.txt](https://github.com/kiwix/kiwix-android-custom/files/13050925/logs1697783883095.txt)

- At this point, we have the following data in storage:

  - /Android/data/org.kiwix.kiwixcustomdwds/files/
    - dwds.zim (355MB)
    - Kiwix/
      - dwds_de_dictionnary_nopic_2023-09-12.zim (0 byte)

- Start the application again, it fails again with same UI error

Logs:
[logs1697784096523.txt](https://github.com/kiwix/kiwix-android-custom/files/13050952/logs1697784096523.txt)

Same content in storage

- Cleanup application storage

There is nothing more in storage at /Android/data/org.kiwix.kiwixcustomdwds

- Start the application, it succeeds

Logs:
[logs1697784135913.txt](https://github.com/kiwix/kiwix-android-custom/files/13050965/logs1697784135913.txt)

- At this point, we have the following data in storage:

  - /Android/data/org.kiwix.kiwixcustomdwds/files/
    - dwds.zim (355MB)

**Comment by kelson42** [comment]
@MohitMaliFtechiz Related to https://github.com/kiwix/kiwix-android/issues/56 IMO. I suspect that fixing https://github.com/kiwix/kiwix-android/issues/56 will fix that one.

**Comment by gouri-panda** [comment]
I think this issue involves how/when we retrieve the asset. @MohitMaliFtechiz We should look into that.

> After installation, we have the following data in storage:
/Android/data/org.kiwix.kiwixcustomdwds/files/
Kiwix/
dwds_de_dictionnary_nopic_2023-09-12.zim (0 byte)

@MohitMaliFtechiz This is from the previous gradle task when we upload the expansion task. We can remove this, we can create file when we copying the asset. Thus we can remove the confusion. The other things i'm not sure.  Maybe looking at the logs will help us.

**Comment by MohitMaliFtechiz** [comment]
>I think this issue involves how/when we retrieve the asset. @MohitMaliFtechiz We should look into that.

Yes, you are right. It is the problem of how we are retrieving the asset.

@benoit74 Thanks for providing the detailed information. I am able to reproduce the error, and placed a fix for it as you can see in below video.


https://github.com/kiwix/kiwix-android-custom/assets/34593983/d9c748fd-2d8e-4b2d-a6f2-63e090df8815

**Comment by kelson42** [comment]
@MohitMaliFtechiz I don't know how many devices are impacted, but fixes seems straight. Please link with PR and make new release.
