### ISSUE TITLE
Remove "caption" string from Minimed infobox

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-android-custom#12]
(maybe this should go to mwoffliner/issues - let me know)
Wikimed mini removes images but keeps captions, which is kind of weird (see image).

![caption](https://user-images.githubusercontent.com/21675885/31376331-de65117e-ada4-11e7-94b2-ca506ebbf712.png)

The infobox string is
| image           =
|caption          = xyz
|nextfield        = blablabla

I'd surmise a simple regexp would do the trick?

**Comment by kelson42** [comment]
This issue was moved to openzim/mwoffliner#168
