### ISSUE TITLE
Continuous Deployement fails to create dummy bundle (even if not specified in the info.json)

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-android-custom#124]
See for example https://github.com/kiwix/kiwix-android-custom/actions/runs/6896284617/job/18762066700#step:7:14.

If not specified, this part of the workflow should not be executed at all. You should probably run in the workflow something like `jq '.app_name' dwds/info.json` (don't forget to install the package for `jq`)

**Comment by kelson42** [comment]
Still not fixed. See https://github.com/kiwix/kiwix-android-custom/actions/runs/7220135963

Please modify the workflow so this part is just not executed, see https://docs.github.com/en/actions/using-jobs/using-conditions-to-control-job-execution

**Comment by MohitMaliFtechiz** [comment]
@kelson42 It is failing to install the `jq`, showing a `permission_denied` error.

![Screenshot from 2023-12-15 17-28-24](https://github.com/kiwix/kiwix-android-custom/assets/34593983/e41b61d4-659a-4918-a507-c7673d7853f8)
