### ISSUE TITLE
Generate Bollywood app

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-android-custom#14]
_From @Popolechien on January 12, 2017 16:8_

A Bollywood app would include articles listed in both Wikiproject Film and WikiProject India (see, e.g. [https://en.wikipedia.org/wiki/Talk:List_of_Bollywood_films_of_2016](https://en.wikipedia.org/wiki/Talk:List_of_Bollywood_films_of_2016)).

_Copied from original issue: openzim/mwoffliner#38_

**Comment by kelson42** [comment]
done, will be online in the next days.

**Comment by kelson42** [comment]
_From @Popolechien on November 21, 2017 15:23_

logo has been uploaded to commons 
[https://commons.wikimedia.org/wiki/File:Bollywood_Kiwix.png](https://commons.wikimedia.org/wiki/File:Bollywood_Kiwix.png)

Can you please generate the app without images, and change the landing page to [https://en.wikipedia.org/wiki/Wikipedia:WikiProject_Film/Offline_Bollywood](https://en.wikipedia.org/wiki/Wikipedia:WikiProject_Film/Offline_Bollywood) ?

**Comment by kelson42** [comment]
The welcome page has been changed. For the rest this is an Android specific topic, I will migrate the ticket.

**Comment by kelson42** [comment]
@Popolechien Now, that we have the ZIM file, you need to create the app on Google Play first with as much details as possible (like screenshots, etc..)

**Comment by RavanJAltaie** [comment]
https://play.google.com/console/u/1/developers/9116215767541857492/app/4974884347233129305/main-store-listing

Play store entry has been uploaded.

**Comment by kelson42** [comment]
AFAIK this app has been published so we can close
