### ISSUE TITLE
Broken wikispecies round icon

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-android-custom#155]
![Screenshot_20231229-161131.png](https://github.com/kiwix/kiwix-android-custom/assets/1029718/671c412d-4571-4877-9fb7-28e6944e9254)

**Comment by kelson42** [comment]
@gouri-panda This problem happens only during install... for mqny custom apps

**Comment by gouri-panda** [comment]
@kelson42 It's not happening only all apps. The icon is very old so we need to update for the new devices dimension. Please let me know which other apps happeninng. And i'll fix ASAP.

**Comment by kelson42** [comment]
wikimedfr at least
