### ISSUE TITLE
Wikimed mini icon has a transparent background

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-android-custom#158]
![Screenshot_20231230-141602.png](https://github.com/kiwix/kiwix-android-custom/assets/1029718/451f0101-8233-4b78-b42a-0ae99a4232dd)

Should be white

**Comment by gouri-panda** [comment]
@kelson42 I have replaced with this Wikimed icon.![icon](https://github.com/kiwix/kiwix-android-custom/assets/43576162/4d00f5a2-0a8b-4f0c-a0f6-898a014233d0)

**Comment by kelson42** [comment]
@gouri-panda Why? This is not what is requested?!

**Comment by gouri-panda** [comment]
@kelson42 That was a play store icon issue. We've uploaded that icon.

**Comment by kelson42** [comment]
@gouri-panda Then why fo you write you have uploaded an other one?!

**Comment by gouri-panda** [comment]
<img width="259" alt="Screenshot 2024-01-02 at 22 20 " src="https://github.com/kiwix/kiwix-android-custom/assets/43576162/2d7ac3b1-271e-4cf0-ac0a-07cee59272a2">

@kelson42 This was the old one. I uploaded the wikimed app icon. So, I thought You should know. It's still under review. If you want we can revert it.

**Comment by kelson42** [comment]
@gouri-panda I don't have requested to use the wikimed logo! Keep the same logo and just put a white background

**Comment by gouri-panda** [comment]
We don't have one. It's in the png format. We can't edit it. If you have white backgound with this logo. Please give me and i'll upload it.

**Comment by kelson42** [comment]
@gouri-panda Have you check in yhe old tickets ?...

**Comment by gouri-panda** [comment]
Yup. I looked the old tickets but its low quality . It doesn't qualify googles policy.

**Comment by kelson42** [comment]
Size is OK in #19, you should be able to do sonething with it.

**Comment by gouri-panda** [comment]
<img width="692" alt="Screenshot 2024-01-02 at 22 55 56" src="https://github.com/kiwix/kiwix-android-custom/assets/43576162/35adf0e7-d59d-46b9-949e-9c91e00a688c">

The size is still low. The highest quality they gave is 412px.

**Comment by gouri-panda** [comment]
@kelson42 Don't worry i've found a tool which allowed me to create size and width that i want. I uploaded it to the playstore and it's in review now.
<img width="692" alt="Screenshot 2024-01-02 at 23 02 29" src="https://github.com/kiwix/kiwix-android-custom/assets/43576162/a9299fa1-a3d6-461c-b37e-12006f913a66">

**Comment by kelson42** [comment]
Still not what is requested.... I will ask someone else.

**Comment by Popolechien** [comment]
I actually do not think it a bad idea to homogeneize and be more consistent in our use of logos. We can ask @siemsie for the backgrounds in any case.

**Comment by gouri-panda** [comment]
@kelson42 The transparent happens because we uploaded the dark theme icon in the playstore. 

>Still not what is requested.... I will ask someone else.

Ok

**Comment by kelson42** [comment]
@MohitMaliFtechiz Please fix respecting requirements.

**Comment by MohitMaliFtechiz** [comment]
> @MohitMaliFtechiz Please fix respecting requirements.

@kelson42 I have checked it, and this issue is with the Play Store icon that we have uploaded. Because that icon is transparent that's why it does not have a white background in the night mode.

> @kelson42 This was the old one. I uploaded the wikimed app icon.

@gouri-panda We should not change the app icon. We just need to add the white background in the existing app icon and update it to the playstore.

**Comment by MohitMaliFtechiz** [comment]
> We don't have one. It's in the png format. We can't edit it. If you have white backgound with this logo. Please give me and i'll upload it. It must have a minum both 512px and 512px width and height.
>Yup. I looked the old tickets but its low quality . It doesn't qualify googles policy.

We have the transparent logo https://github.com/kiwix/kiwix-android-custom/blob/main/wikimedmini/icon.png with the playstore recommended width and height, we can add the white background to it.

**Comment by kelson42** [comment]
> > We don't have one. It's in the png format. We can't edit it. If you have white backgound with this logo. Please give me and i'll upload it. It must have a minum both 512px and 512px width and height.
> >Yup. I looked the old tickets but its low quality . It doesn't qualify googles policy.
> 
> We have the transparent logo https://github.com/kiwix/kiwix-android-custom/blob/main/wikimedmini/icon.png with the playstore recommended width and height, we can add the white background to it.

@MohitMaliFtechiz LGTM. Please just do it. I have made this trivial request literaly 4 days ago and we are 25 items further in the ticket is still not done! I don't get it!

**Comment by MohitMaliFtechiz** [comment]
@kelson42 The app logo has been updated on the Play Store.

| normal mode  | night mode |
| ------------- | ------------- |
| ![1704375716234](https://github.com/kiwix/kiwix-android-custom/assets/34593983/e31ac9c5-6767-40e1-8339-06e7143e1d8d)  | ![1704375715991](https://github.com/kiwix/kiwix-android-custom/assets/34593983/9a271efd-d150-44d1-9f1f-398f584a66f4) |
