### ISSUE TITLE
Update Arabic Wikimed landing page

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-android-custom#16]
The new, updated landing page for Arabic Wikimed can be found here:

https://ar.wikipedia.org/wiki/%D9%88%D9%8A%D9%83%D9%8A%D8%A8%D9%8A%D8%AF%D9%8A%D8%A7:%D9%85%D8%B4%D8%B1%D9%88%D8%B9_%D9%88%D9%8A%D9%83%D9%8A_%D8%B7%D8%A8/%D9%85%D8%B1%D8%AC%D8%B9_%D8%A8%D8%AF%D8%A7%D9%8A%D8%A9_%D8%A7%D9%84%D8%AA%D8%B7%D8%A8%D9%8A%D9%82_%D8%A7%D9%84%D8%B7%D8%A8%D9%8A2

**Comment by kelson42** [comment]
done
