### ISSUE TITLE
How do we get to test apps in testing phase?

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-android-custom#163]
Asking specifically for Wikimed Ukrainian, Bollywood offline and the Arabic wiktionary - they're all listed as `internal testing` (and I'm a tester) yet I can't seem to find them listed?

**Comment by gouri-panda** [comment]
@Popolechien You need an internal testing URL. One way You can find it is in the internal testing -> testers. If you want i can give you in private for all 3 apps.

**Comment by gouri-panda** [comment]
It's been solved.
