### ISSUE TITLE
Release CAN / AFCON apps

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-android-custom#164]
We have prepared to entries for the ongoing Coupe d'Afrique des Nations ([in French](https://play.google.com/console/u/0/developers/9116215767541857492/app/4973339428494809537/app-dashboard?timespan=thirtyDays)) / Africa Cup of Nations ([in English](https://play.google.com/console/u/0/developers/9116215767541857492/app/4975563123436841775/app-dashboard?timespan=thirtyDays))

Both app entries have been created on the playstore, and the corresponding ZIM files can be found here: [English](https://drive.farm.openzim.org/custom%20apps/CAN%20App%20-%20English/All%20Articles%20/CANAllArticlesEN-1ed6e94c6348_2024-01.zim) / [French](https://drive.farm.openzim.org/custom%20apps/CAN%20App%20-%20French/All%20Articles%20-%20FR/CANAllArticlesFR-4546453e6f9d_2024-01.zim)

Please create the corresponding apps for testing

**Comment by gouri-panda** [comment]
@Popolechien I created the zim URL from the URL domain that you gave. Let me know if you want to change it.
