### ISSUE TITLE
Update and release WikiVoyage (Offline Reiseführer)

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-android-custom#168]
There is a new zim at https://mirror.download.kiwix.org/zim/wikivoyage/wikivoyage_de_all_maxi_2024-01.zim and the app itself should be updated (Google tells me it aims at API 25 instead of 33). Prep it for open testing please.

**Comment by gouri-panda** [comment]
Blocked by https://github.com/kiwix/kiwix-android/issues/3677
