### ISSUE TITLE
Positive search result in Wikimed fails to send user to corresponding article.

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-android-custom#17]
From OTRS:
I'm using the wikimed app. 
 Version : 2017-08
Buid : 1172141

Whenever I type gongylonema pulchrum , I get the search results but when I tap on it.. nothing happens... It doesn't direct me to the content.

**Comment by kelson42** [comment]
I confirm the bug... but this is more for the Kiwix repo.

**Comment by kelson42** [comment]
This issue was moved to kiwix/kiwix-android#567
