### ISSUE TITLE
The Arabic Wiktionary app crashed!

### ISSUE THREAD

**Issue by sadiqui** [kiwix/kiwix-android-custom#170]
I was using a Samsung A02s running Android 12.

During the testing, I ran the Arabic Wiktionary app for over 15 minutes. Initially, the app worked well, and I was impressed by its robust functionality. However, after leaving it for a while and returning, I went to opened tabs and attempted to close some of them. At that point, the app crashed, and I received a blue full-screen message. I have attached the message and the generated txt logs file to this report.

With appreciation.

<img src="https://github.com/kiwix/kiwix-android-custom/assets/143453064/b32fbe90-ee9f-4a62-a28d-2ebf17f22a21" alt="Screenshot_20240121-114058" width ="100">

<img src="https://github.com/kiwix/kiwix-android-custom/assets/143453064/54ffcd96-8e03-4f0a-8d1b-567abfdcf725" alt="Screenshot_20240121-114129" width="100">

[logs1705833669393.txt](https://github.com/kiwix/kiwix-android-custom/files/14002072/logs1705833669393.txt)

**Comment by gouri-panda** [comment]
@sadiqui Thanks! We'll look into that.

**Comment by MohitMaliFtechiz** [comment]
Hi @sadiqui Thanks for opening the issue and providing the logs, crash logs and scenario of crash is very same as we have just fixed in https://github.com/kiwix/kiwix-android/issues/3790.

**Comment by sadiqui** [comment]
Hi @MohitMaliFtechiz,
Thank you for the follow-up! I really appreciate the effort.
Your contributions are invaluable to improving the project.
Best regards.
