### ISSUE TITLE
Move dwds application to their organization(play console account).

### ISSUE THREAD

**Issue by MohitMaliFtechiz** [kiwix/kiwix-android-custom#187]
Now `dwds` wants to publish thier application in their organization, and currently, it is published in the internal testing in kiwix organization.

So we have to move this `dwds` application to their(client organization).

Here are the steps on how we can move the dwds app to their organization.
1. Go to settings in kiwix play console account, and click on App transfer.
    
![Screenshot from 2024-09-28 17-58-55](https://github.com/user-attachments/assets/e55a1e38-1691-4261-be4b-a7ad2212e0e0)
![image](https://github.com/user-attachments/assets/6faa3c15-51a3-49be-9a8f-f20e0bfad966)

2. Here we need some details:
    1. Your transaction ID(kiwix organization transaction id) When we purchased the Google Play console this transaction id came in our Gmail account.
    2. New developer account (`Developer ID` of dwds play console account, Which we can find on the `Account details` page).
    3. New account transaction ID (Dwds organization transaction ID, as we need for Kiwix in 1 step).
     ![image](https://github.com/user-attachments/assets/41192e93-527b-4e1d-9461-325c35e1f71b)

    4. Select the `Reason for transfer`, and `Bussiness relationship`.
   
3. Select the dwds app for transfer. at the end and click on `Review and transfer`.
    
![image](https://github.com/user-attachments/assets/57a4ea11-ccc6-4574-81d0-4d8fa4d70e71)

It will take 2 days to transfer the application to dwds organization.

@kelson42 I do not have access to transferring the application, can you please do these steps? @gremid please provide your `Developer ID`, `transaction ID` to @kelson42 so that he can move dwds app to your organization.

**Comment by kelson42** [comment]
@MohitMaliFtechiz We should remove the app from our organisation and the app will newly published directly to the new org. Please handle the move directly with @gremid.

**Comment by MohitMaliFtechiz** [comment]
@kelson42 After moving the application it will be automatically removed from our organization and will be published to the dwds organization with the same package name(current package name `org.kiwix.kiwixcustomdwds`). Also, dwds do not require setting up all the things in PS like `Store listings` etc. All the existing setups will move to dwds organization.

> and the app will newly published directly to the new org.

We can not publish the dwds application with the same package name to their organization(Only a way to move the existing app to their organization. Otherwise, we need to change the package name of the application). Is dwds want to publish the application with a new package name?

**Comment by kelson42** [comment]
> Is dwds want to publish the application with a new package name?

Would be simpler to keep the same indeed.

**Comment by MohitMaliFtechiz** [comment]
> Would be simpler to keep the same indeed.

Okay, then we should move the application to the dwds organization to use the same `package name`.

**Comment by kelson42** [comment]
I have initiated the transfer on the Google Play Store

**Comment by kelson42** [comment]
The transfer has been completed
