### ISSUE TITLE
Dwds app failed to upload in thier organization.

### ISSUE THREAD

**Issue by MohitMaliFtechiz** [kiwix/kiwix-android-custom#191]
The service JSON @gremid provided us does not have the necessary permission to upload the application in their organization.

See the last CD failed https://github.com/kiwix/kiwix-android-custom/actions/runs/11613366257/job/32338996270 with error:

```kotlin
> com.google.api.client.googleapis.json.GoogleJsonResponseException: 403 Forbidden
  POST https://androidpublisher.googleapis.com/androidpublisher/v3/applications/org.***.***customdwds/edits
  ***
    "code" : 403,
    "errors" : [ ***
      "domain" : "global",
      "message" : "The caller does not have permission",
      "reason" : "forbidden"
    *** ],
    "message" : "The caller does not have permission",
    "status" : "PERMISSION_DENIED"
  ***

```

Also, I have tried to upload the application locally with @gremid provided JSON file, but the same error has occurred.
![Image](https://github.com/user-attachments/assets/39a72f66-9915-4dea-94bc-f660fdb3c096)

@gremid Can you please check if the permission for this user `dws-app-publication@dwds-app.iam.gserviceaccount.com` is properly added in playStore. Something like this: 

![Image](https://github.com/user-attachments/assets/cc918968-ed8c-4afc-b21b-a15675a8903a)

We need `Release apps to testing tracks` permission for this Gmail account.

**Comment by gremid** [comment]
Added the mentioned persmissions. Thanks, @MohitMaliFtechiz, for documenting the necessary steps so well!

**Comment by MohitMaliFtechiz** [comment]
@gremid Thanks for adding the permission, The latest dwds app is uploaded in internal testing in your organization https://github.com/kiwix/kiwix-android-custom/actions/runs/11659642493/job/32460545038, you can check this under the `Testing`. Currently, it is in `draft` you have to manually release the application in internal testing.

![Image](https://github.com/user-attachments/assets/6c57503e-9255-4254-90b4-c8be77377011)
