### ISSUE TITLE
Is it OK to submit the Wikivoyage app to F-Droid?

### ISSUE THREAD

**Issue by nicolas-raoul** [kiwix/kiwix-android-custom#23]
Many Android users don't have access to Google Play, for instance in China or LineageOS users.
Making the app available on F-Droid would allow these people to use the app.
The Wikivoyage community is also asking for this.

We could just take the source code and build/publish it, but F-Droid has a principle of asking app developers before doing it, so you just need to write "OK" here :-)

Thanks!

**Comment by kelson42** [comment]
@nicolas-raoul Someone made that recently an this is totally broken. Does not work, at least for me. We should fix it or ask to remove it.

**Comment by nicolas-raoul** [comment]
@kelson42 Do you mean that when you run [Wikivoyage European Travels](https://f-droid.org/en/packages/org.kiwix.kiwixcustomwikivoyageeurope/), you get the error below?
![Screenshot_20191225-171131_Wikivoyage European Travels](https://user-images.githubusercontent.com/99590/71438688-0ee9a100-273a-11ea-89f4-26c501cf6d23.jpg)
I will report it, so that the app gets either fixed or removed.
Thanks for the feedback!

**Comment by kelson42** [comment]
@nicolas-raoul yes

**Comment by licaon-kter** [comment]
It's about OBBs or what is missing?

**Comment by kelson42** [comment]
@licaon-kter No clue, I don't have built or studied this FDroid app.

**Comment by licaon-kter** [comment]
Clue? What are the conditions to show that error? What is missing? Why is it "corrupted"?

**Comment by kelson42** [comment]
@licaon-kter Ask the packager, not us, we don't have published this app on FDroid.

**Comment by licaon-kter** [comment]
Could you please answer some of the questions? F-Droid compiles the code as it is..."corrupted" messages appears as the code prescribes it.

**Comment by kelson42** [comment]
@licaon-kter Our custom apps are conceived to run with the Google Play store extension system. FDroid does not provide this system. AFAIK there is no surprise it does not work. If you have a specific question about Kiwix for Android compilation, please open an other ticket. This a ticket asking us to port the Wikivoyage app to Froid, not a ticket to debug such an app built by someone who AFAIK has never been in touch with us and which AFAIK can simply not work that way.

**Comment by licaon-kter** [comment]
Looking at the APK I see that only `armeabi` has a `libcontent.so` while all the other archs do not.

**Comment by macgills** [comment]
@licaon-kter this is quite an outdated app, the corrupt message shows when we couldn't find an obb file. Nowadays we just go off and download the zim file if there is no obb found.
We hope to extend our build system to package zim files inside apks for releases outside the app store or completely offline but that is a ways away yet

**Comment by licaon-kter** [comment]
Yes, we download the ZIM but the packager thought that having that once in a single arch would let the other use it too, which proved to be false.

**Comment by macgills** [comment]
This will also stop working in the future as for now we are not supporting "embedded" zims until upgrades are made to kiwixlib to work with inputStreams/assetFileDescriptors to avoid unpacking the zim files and using twice the space on the device

**Comment by kelson42** [comment]
I think the answer to the original question is:  no. At least as long as one of these things does not work properly:
* FDroid extension system
* Kiwix ability to deal with embedded ZIM files
* Third party download proven to work fine

@licaon-kter I'm also not happy to have our code packaged "wildly" on FDroid, without collaboration with us... and finally not working fine. I would like to remove it.

**Comment by licaon-kter** [comment]
@kelson42 https://gitlab.com/fdroid/fdroiddata/-/merge_requests/6315
