### ISSUE TITLE
Space beneath every image

### ISSUE THREAD

**Issue by ARR8** [kiwix/kiwix-android-custom#24]
App version: Wikivoyage 2018-12
Android version: 9, no Google Play Services
![screenshot_20190108-105136_wikivoyage](https://user-images.githubusercontent.com/8064135/50842032-d3ee3200-135d-11e9-963e-8be2686e7566.png)

**Comment by kelson42** [comment]
@ARR8 Thx, I suspect a problem with the content itself. Should have a look in detail

**Comment by kelson42** [comment]
This issue was moved to openzim/mwoffliner#495
