### ISSUE TITLE
Wikivoyage: Tapping on map marker number unhandled

### ISSUE THREAD

**Issue by ARR8** [kiwix/kiwix-android-custom#25]
App version: Wikivoyage 2018-12
Android version: 9, no Google Play Services

The markers are also always numbered 1.  
See error at bottom of image
![screenshot_20190108-105902_wikivoyage](https://user-images.githubusercontent.com/8064135/50842431-93db7f00-135e-11e9-915d-5776def0fae4.png)

**Comment by kelson42** [comment]
This issue was moved to openzim/mwoffliner#494
