### ISSUE TITLE
Wikivoyage: Extraneous Wikipedia and Wikidata icons in listings

### ISSUE THREAD

**Issue by ARR8** [kiwix/kiwix-android-custom#26]
App version: Wikivoyage 2018-12
Android version: 9, no Google Play Services

These could either have the link or be hidden. As-is, they interrupt the flow of the text and mislead.

![screenshot_20190108-110330_wikivoyage](https://user-images.githubusercontent.com/8064135/50842609-fa609d00-135e-11e9-89c6-07bc5600a50c.png)

**Comment by kelson42** [comment]
This has to do with the scraper `mwoffliner`. Moving the ticket.

**Comment by kelson42** [comment]
This issue was moved to openzim/mwoffliner#493
