### ISSUE TITLE
add readme

### ISSUE THREAD

**Issue by matkoniecz** [kiwix/kiwix-android-custom#28]
At this moment it is completely unclear what is in this repo. I got referred here with claim that it is source of https://play.google.com/store/apps/details?id=org.kiwix.kiwixcustomwikivoyage app

Also, such source code is not really useful without instruction how it can be used

**Comment by kelson42** [comment]
Yes, looks to the kiwix-android repo, to get the code.

**Comment by matkoniecz** [comment]
So https://github.com/kiwix/kiwix-android has code that is build using https://github.com/kiwix/kiwix-build ?

So what is in this repo? Customization that is imported by https://github.com/kiwix/kiwix-build ?

**Comment by kelson42** [comment]
@matkoniecz This is only the custom configuration to build one of our custom app wikivoyage, wikimed, ... based on kiwix Android code base.

**Comment by kelson42** [comment]
Done
