### ISSUE TITLE
Finish to update configuration file to new build system.

### ISSUE THREAD

**Issue by mgautierfr** [kiwix/kiwix-android-custom#3]
New build system using `kiwix-build` need the `zim_url` attribute.
There is no more need to `version` or `content_version` as it is automatically set by build system.

**Comment by mgautierfr** [comment]
I've made a first pass few days ago.
But now, zims have changed (we must use "_novid", not normal zim).

**Comment by kelson42** [comment]
@mgautierfr Agree, but zim_url should be removed.

Everything should be in zim_file like before:
* it can be a url or a path
* path can be absolut or relative
* if relative, relative to the info.json

**Comment by mgautierfr** [comment]
There is something some one us misses here :

I've re-write the build_custom_app script in the intent to have this script run using travis.
This means that all "real" operations are made on travis computers, not on the local one.

In this context, have a local path is a non sense. This file will not exists on the travis computers and we cannot upload files into a build.
Scripts running on travis NEED a url to be able to download the zim file.

More over, the json info file is directly taken from the git repository, and I would strongly disagree with a committed json-file with a "link" to a non existent local path.

So either we could not have a local zim path (and we cannot do "like before"), or either I have to rewrite a bit the script to allow it to run locally.

For now the only way to build a custom app locally is to follow this [documentation](https://github.com/kiwix/kiwix-build/wiki/Build-and-publish-a-custom-app-locally-(without-travis)).
This document use only once the `zim-path` hidden option I've recently added, mainly as a workaround because travis build is broken (on travis side).

**Comment by kelson42** [comment]
This ticket is oudated.
