### ISSUE TITLE
Wikimed mini opens on empty/blank screen

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-android-custom#32]
The issue remains when I close/ reopen the app. Clicking on Home does not take me anywhere. Closing the currently open article brings me back to a blank screen as well.
Version 2018-08 build 1182421. Other than that the app works fine as far as I can tell.

**Comment by kelson42** [comment]
This is a bug impacting android 9 and has been fixed weeks ago. This will be automatically fixed with new custom app releases.
