### ISSUE TITLE
Which format works best for layout design files?

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-android-custom#46]
We've concluded the design contest for the Wiktionary app, and the designer asks if  is it okay if she sends the XD file of these screens instead of PSD or Sketch.

@macgills Is there any significant difference for us between these file formats?

**Comment by kelson42** [comment]
@Popolechien None of them are free AFAIK :( The original one like you have + PNG would be fine IMO.

**Comment by macgills** [comment]
I don't particularly know. Usually I would get a pdf.

If it is easy to open xd files without particular software that requires a license then it is all good otherwise it is quite bad
