### ISSUE TITLE
Update Arabic Wikimed app 

### ISSUE THREAD

**Issue by alanajjar** [kiwix/kiwix-android-custom#47]
Hello,

Last zim is from September 2018 and the content on the app is probably older. We have many pings on that on Arabic Wikipedia WikiProject Medicine and on Arabic Wikipedia official Facebook page. Thank you.

**Comment by kelson42** [comment]
@alanajjar Yes, should happen within two weeks from now

**Comment by alanajjar** [comment]
@kelson42 so fast! 
Thanks on advance

**Comment by alanajjar** [comment]
Hello @kelson42
Any updates?

**Comment by Popolechien** [comment]
@alanajjar Well, we've just rolled out the automated updates already - shouldn't be long if it hasn't been done yet.

**Comment by alanajjar** [comment]
Thanks @Popolechien
I'm still waiting, and when update come, I'll comment here. 

Thanks a lot all

**Comment by kelson42** [comment]
@alanajjar @Popolechien I just have released a new version, should be available to download in the Google Play store in the next hours. Thank you for your patience.

**Comment by alanajjar** [comment]
Thanks @kelson42 

Updated and I announced about that on arwiki wikimedproject.
