### ISSUE TITLE
Generate Wiktionary Playstore entry

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-android-custom#49]
Should include a short description of the app and the usual shizzle.

**Comment by kelson42** [comment]
All the play store stuff is handled in the Play store, we don't configure it here. Just for clarification.

**Comment by Popolechien** [comment]
I know it's more for me to know what to do, following #14

**Comment by RavanJAltaie** [comment]
I will create the Apps and fill the entry details for English Wiktionary, Arabic Wiktionary as a start.

**Comment by Popolechien** [comment]
@RavanJAltaie For the Arabic Wiktionary playstore app you may want to replace the Wiktionary logo with a simple Arabic letter (either ق or ك ?) We have had issues in the past trying to use WMF logos on the playstore which led to the apps being suspended, and discussions with WMF legal are... long.

**Comment by RavanJAltaie** [comment]
@Popolechien Updated!
