### ISSUE TITLE
Update Wikimed AR app logo

### ISSUE THREAD

**Issue by alanajjar** [kiwix/kiwix-android-custom#56]
https://play.google.com/store/apps/details?id=org.kiwix.kiwixcustomwikimedar

Current logo include sentence (medical encyclopedia) without offline symbol
https://commons.wikimedia.org/wiki/File:Wikimed_Arabic_Logo.svg

New logo include sentence (Medical Wikipedia) + offline symbol
https://commons.wikimedia.org/wiki/File:Wikimed_Arabic_Logo_2.svg

Note: I updated the interface page of the app to appear on next release
https://w.wiki/Grh

**Comment by Popolechien** [comment]
I've updated the logo link in the zimfarm receipe.

**Comment by kelson42** [comment]
> I've updated the logo link in the zimfarm recipe and on the PlayStore.

This is not a bad move, but this does not fix this ticket at all.

**Comment by kelson42** [comment]
@gouri-panda If you could do that quickly please.... we have been so bad to not implement this immediatly and now we are 3 years later!

**Comment by kelson42** [comment]
@gouri-panda ???

**Comment by gouri-panda** [comment]
@kelson42 Sorry! On it.

**Comment by gouri-panda** [comment]
@kelson42 I believe we've updated the logo.

**Comment by kelson42** [comment]
Please verify and secure this has been done, there is no PR related to this issue, this is not normal. Link with a commit at least.

**Comment by gouri-panda** [comment]
<img width="238" alt="Screenshot 2023-12-28 at 18 25 58" src="https://github.com/kiwix/kiwix-android-custom/assets/43576162/6c90ece5-1994-4a4e-83b2-dd598f421b01">

@kelson42 both the requested image(with offline logo)  and this current images are the same IMO. Created by here https://github.com/kiwix/kiwix-android-custom/commit/5fb8063f934448ab827f448725b95a65f71d70b1 which was before the ticket. Am I missing something?

**Comment by kelson42** [comment]
-
