### ISSUE TITLE
WikiMed app- Credits#Contributors color on night mode

### ISSUE THREAD

**Issue by alanajjar** [kiwix/kiwix-android-custom#57]
Hello,

On Android WikiMed app (I tired EN. & AR.), the blue color of (Contributors) links on Credits section on night mode appear painful for eyes and can't be read easily.

I notice that personally and from another friends (3) who using the app.

Thanks.
![Screenshot_2020-02-08-16-52-47](https://user-images.githubusercontent.com/20701355/74087354-048a2900-4a94-11ea-8f47-378bf121c849.png)

**Comment by kelson42** [comment]
@alanajjar This has been fixed a few weeks ago. Next release will be OK.
