### ISSUE TITLE
Update tagging release methodology

### ISSUE THREAD

**Issue by macgills** [kiwix/kiwix-android-custom#63]
Currently we push a tag of a name eg `phet` to trigger a release of a custom app against `master` of `kiwix-android`

This leads to some confusion about what version of the app is published for a custom app.

We should update our workflow and tagging procedure so that we push the tag `phet:3.3.4` on this repo to do a release of `phet` with `3.3.4` of `kiwix-android`

**Comment by kelson42** [comment]
@macgills Good to me, but then we need to avoid putting `phet:master` ;)

**Comment by kelson42** [comment]
The publishing is now done based on github releases, so there is no ambiguity anymore
