### ISSUE TITLE
Impossible to build custom apps with Kiwix Android 2.4

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-android-custom#64]
The CI fails to go through because the install version of NDK is not the right one (the same as in kiwix/kiwix-android). See https://github.com/kiwix/kiwix-android-custom/runs/2296262609?check_suite_focus=true

```
Execution failed for task ':custom:stripWikispeciesReleaseDebugSymbols'.
> No version of NDK matched the requested version 22.0.7026061. Versions available locally: 21.4.7075529, 21.4.7075529, 21.4.7075529
```

I believe the problem is that we should in kiwix-android-custom request to install the same NDK as for kiwix/kiwix-android... for the moment it just have the default version

**Comment by kelson42** [comment]
@gouri-panda Could you please have a look to this bug please? This is basically the only thing I'm aware of currently stopping us to put 2.4.4 in beta.

**Comment by gouri-panda** [comment]
@kelson We can manually add NDK version that we have. Currently `kiwix-andorid` version uses `22.0.7026061`. We can add NDK version it asks for i.e `21.4.7075529` and  `21.4.7075529`. More info [here](https://github.com/gradle/gradle/issues/12440#issuecomment-606188282)

**Comment by kelson42** [comment]
@gouri-panda Sounds good to me, would you be able to try that and see if it works? I'm not sure about how to test this without making a new release... maybe you know? In worse case just make a new release of wikispecies app.

**Comment by kelson42** [comment]
Fixed thx to @gouri-panda
