### ISSUE TITLE
Target Android 11 before November 2021

### ISSUE THREAD

**Issue by gouri-panda** [kiwix/kiwix-android-custom#65]
More info at  https://github.com/kiwix/kiwix-android/issues/2516

**Comment by kelson42** [comment]
@gouri-panda This is important indeed. We will release soon 3.4.5 and this is important that new custom apps are based on it.

**Comment by kelson42** [comment]
@gouri-panda What is the status here? Is that still a valid issue?

**Comment by gouri-panda** [comment]
@kelson42 It's not a valid issue anymore. We already implemented Android 11.  We missed this ticket :)

**Comment by kelson42** [comment]
@gouri-panda thx
