### ISSUE TITLE
Update WikiVoyage apps

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-android-custom#71]
Both Wikivoyage apps (the regular one and the Europe one) were last updated in January 2020 and seem to describe Ukraine as a pleasant and funky destination o_0

**Comment by Jaifroid** [comment]
Seems urgent. See also #80 -- the current one is no-longer findable in Play Store.

**Comment by gouri-panda** [comment]
Ok @Jaifroid On it.

**Comment by gouri-panda** [comment]
Both the wikivoyage and wikivoyage europe apps have been updated.

**Comment by kelson42** [comment]
Wikivoyage europe is not updated, see last publishing date https://play.google.com/store/apps/details?id=org.kiwix.kiwixcustomwikivoyageeurope

**Comment by gouri-panda** [comment]
@kelson42 In the console it says it has been updated. It's in the production.Weird 🤔

**Comment by kelson42** [comment]
@gouri-panda Please try to find solution, just look to the reasons given. It's the same as https://github.com/kiwix/kiwix-android-custom/issues/103#issuecomment-1793468855.... Google has clearly said that Apps not supporting properly Android13 won't be able to update anymore.

**Comment by Jaifroid** [comment]
It's showing for me in the Play Store, and I've just installed it. It's the latest!

**Comment by kelson42** [comment]
@gouri-panda Any reason why this ticket is still open?

**Comment by gouri-panda** [comment]
@kelson42 We can close this now.
