### ISSUE TITLE
Release Ukrainian Wikimed app

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-android-custom#72]
Playstore entry has been created (https://play.google.com/console/u/0/developers/9116215767541857492/app/4972558197069908415/releases/overview) and the zim file needed is at https://download.kiwix.org/zim/wikipedia/wikipedia_uk_medicine_maxi_2023-02.zim

**Comment by Popolechien** [comment]
Update: file is now at https://download.kiwix.org/zim/wikipedia/wikipedia_uk_medicine_maxi_2023-10.zim but the bottom line is rather to make sure that we get the latest version.

**Comment by gouri-panda** [comment]
@kelson42 @Popolechien Should we release this now?

**Comment by kelson42** [comment]
in internal testing please
