### ISSUE TITLE
Finish generation Bollywood App

### ISSUE THREAD

**Issue by RavanJAltaie** [kiwix/kiwix-android-custom#73]
The play store entry for Bollywood offline App has been uploaded.
Please create the app itself (package Kiwix+zim file).
https://play.google.com/console/u/1/developers/9116215767541857492/app/4974884347233129305/main-store-listing

#14

**Comment by Popolechien** [comment]
Zim file is https://download.kiwix.org/zim/wikipedia/wikipedia_en_indian_cinema_maxi_2023-02.zim

**Comment by gouri-panda** [comment]
@kelson42 @Popolechien Should we release this now?

**Comment by kelson42** [comment]
in internal testing please
