### ISSUE TITLE
Finish Generating Arabic Wiktionary Offline App (ويكاموس بدون إنترنت) 

### ISSUE THREAD

**Issue by RavanJAltaie** [kiwix/kiwix-android-custom#75]
Could you please help in finishing generating Arabic  Wiktionary Offline (ويكاموس بدون إنترنت) App?
The play store entry has been uploaded.
Please create the app itself (package Kiwix+zim file).
https://play.google.com/console/u/1/developers/9116215767541857492/app/4975368414199853567/main-store-listing
The Zim file is:

https://download.kiwix.org/zim/wiktionary/wiktionary_ar_all_maxi_2023-03.zim

https://github.com/kiwix/kiwix-android-custom/issues/49

**Comment by Popolechien** [comment]
Update: file is https://download.kiwix.org/zim/wiktionary/wiktionary_ar_all_maxi_2023-10.zim but the bottom line is that when the app is created we should take the latest wiktionary_ar_all_maxi

**Comment by Popolechien** [comment]
@gouri-panda Do you have a ballpark figure of when we could see a test app uploaded to the store?

**Comment by gouri-panda** [comment]
@Popolechien sure!,  I need the app icon to create a valid custom folder and publish it. I'll create the  test app by the end of the day.

**Comment by Popolechien** [comment]
Awesome. @RavanJAltaie has the logo. Which size do you need it to be, and where do you want it stored?

**Comment by gouri-panda** [comment]
@Popolechien  we'll create a variety of app icon for the a number if devices. We'll store in the kiwix-android-custom repo. @RavanJAltaie Can you give me the app icon? Thanks!

**Comment by RavanJAltaie** [comment]
Here is the logo  [here](https://drive.farm.openzim.org/Apps/Arabic%20Wiktionary%20Logo.jpg)
@gouri-panda

**Comment by gouri-panda** [comment]
The new Arabic Zim file is live on the play store now. We can close this.

**Comment by Popolechien** [comment]
@gouri-panda thanks - can you please push it for internal testing?

**Comment by gouri-panda** [comment]
@Popolechien It's already in the internal testing.

**Comment by Popolechien** [comment]
Are you sure? I see it listed as Draft only (when DWDS for instance is Internal testing and Bollywood/Wikimed UK are draft/internal testing on my dashboard)

**Comment by gouri-panda** [comment]
@sorry! I misunderstood the ticket 😪

**Comment by gouri-panda** [comment]
@sorry! I misunderstood the ticket 😪

**Comment by gouri-panda** [comment]
@Popolechien Sorry! I misunderstood the ticket with the wikimed AR. I'm creating this now.

**Comment by gouri-panda** [comment]
@Popolechien Done. Let me know if you need anything.
