### ISSUE TITLE
Update Custom Apk to Bundle

### ISSUE THREAD

**Issue by gouri-panda** [kiwix/kiwix-android-custom#78]
We want to move our existing Android APKs to the Android App Bundle format so that we can take advantage of its benefits, such as smaller app sizes, optimized APKs for different device configurations, and dynamic delivery of features and resources.

**Comment by kelson42** [comment]
@MohitMaliFtechiz @gouri-panda I though this as been fixed and we had only to sort-out the signature topic!?

**Comment by MohitMaliFtechiz** [comment]
@gouri-panda , We have already did this in https://github.com/kiwix/kiwix-android/pull/3292 and fixed the error while uploading the bundle on playstore in https://github.com/kiwix/kiwix-android/pull/3297 . Have you opened this ticket to secure that any error occurs while uploading the bundle?

**Comment by gouri-panda** [comment]
@MohitMaliFtechiz @kelson42 Sorry I didn't explain clearly in the description! In the github action file we should change this. We are using the same previous command that we removed in https://github.com/kiwix/kiwix-android/pull/3297

**Comment by MohitMaliFtechiz** [comment]
> @MohitMaliFtechiz @kelson42 Sorry I didn't explain clearly in the description! In the GitHub action file, we should change this. We are using the same previous command that we remove

@gouri-panda Okay got you, are you working on this? or should I create a PR for this?
