### ISSUE TITLE
Wikivoyage custom app not accessible by searching in Play Store - abandoned?

### ISSUE THREAD

**Issue by Jaifroid** [kiwix/kiwix-android-custom#80]
Although it can be found in a browser, on my Android phone, searching for "Wikivoyage" or "Wikivoyage Kiwix" or "Wikivoyage offline" inside the Play Store app doesn't find the app. Searching for "Wikivoyage Kiwix" shows the WikiMed custom app as the second choice (after the main Kiwix app). And it's not possible to open the relevant Play Store install page from a browser (at least for me): I get "This App is not available for your device" (!). My device is a bog-standard midrange Samsung Android running Android 12.

I also note that the Wikivoyage English apk is not updated since January 2020, over 3 years ago #71. If possible, now would be a good time to update it, because all the content updates for the last year have finally been incorporated into the April 2023 Wikivoyage English ZIM (now ~1GB), if the [publish actions](https://github.com/kiwix/kiwix-android-custom/actions) can be fixed. Might it be worth building it manually as an exception if the actions can't be fixed yet?

Finally, if the Play Store version is not updateable any more, it should be a priority to get an F-Droid version out #30.

Sorry if I'm stating the obvious, but it seems urgent to clarify the status of the Android custom apps. Apart from WikiMed, they appear abandoned (I'm sure this isn't the case or the intention).

**Comment by kelson42** [comment]
I think this is because we need to fix things. In the meantime the Play Store has decided to hide the app.

**Comment by kelson42** [comment]
@Jaifroid Thank you for reporting this. I suspect that to a large extend the problem is fixed. Could you verify again. If this is still not working could you please tell me which version of Android you have?

**Comment by kelson42** [comment]
@Jaifroid Look as well to https://github.com/kiwix/kiwix-android-custom/issues/30

**Comment by Jaifroid** [comment]
I confirm I am now able to find and install the Wikivoyage app on my Android 12 device!

Congratulations on reviving it, and with the latest ZIM too! 🎉
